#!/usr/bin/env python3
"""gen_names_auto.py -- data.db의 IT 종목명을 한자 음독으로 변환해 names_auto.py 생성.

Layer 1 of the naming stack. Purely mechanical: every company in
groups.IT_INDUSTRIES gets a Korean reading of its Chinese name. Hand-picked
names live in names.py (layer 2) and win over anything here.

    python gen_names_auto.py

Rerun after widening groups.IT_INDUSTRIES or after new listings appear.
Any hanja missing from hanja_kr.HANJA is reported so the table can be extended.
"""

from __future__ import annotations

import os
import sqlite3
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import bom_groups
import groups
from hanja_kr import HANJA, to_korean

DB = os.path.join(HERE, "data.db")
OUT = os.path.join(HERE, "names_auto.py")


def main() -> int:
    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row

    counts = [(r["ym"], r["n"]) for r in conn.execute(
        "SELECT ym, COUNT(*) n FROM revenue GROUP BY ym ORDER BY ym")]
    mx = max(n for _, n in counts)
    ref = max(ym for ym, n in counts if n >= 0.7 * mx)

    # The IT filter plus every bom_groups code. Without the union, a BoM stock
    # whose official industry sits outside the filter (8996 高力 is 電機機械業)
    # would have no Korean reading at all and fall back to its Chinese name.
    inds = list(groups.IT_INDUSTRIES)
    bom = bom_groups.all_codes()
    ph = ",".join("?" * len(inds))
    cph = ",".join("?" * len(bom))
    rows = list(conn.execute(
        f"SELECT r.code, r.name, r.industry, r.rev_month_k, m.name_en "
        f"FROM revenue r LEFT JOIN company m ON m.code = r.code "
        f"WHERE r.ym=? AND (r.industry IN ({ph}) OR r.code IN ({cph})) "
        f"ORDER BY r.rev_month_k DESC", (ref, *inds, *bom)))
    conn.close()

    extra = [r["code"] for r in rows
             if r["industry"] not in set(inds) and r["code"] in set(bom)]
    print(f"gen_names_auto.py  ref={ref}  companies={len(rows)}")
    print(f"  bom_groups codes outside the IT filter: {extra or 'none'}")
    print(f"  hanja table: {len(HANJA)} characters")

    missing = Counter()
    out, unconverted = {}, []
    for r in rows:
        kr, miss = to_korean(r["name"] or "")
        out[r["code"]] = kr
        for ch in miss:
            missing[ch] += 1
        if miss:
            unconverted.append((r["code"], r["name"], kr, "".join(miss)))

    if missing:
        print(f"\n  !! {len(missing)} hanja not in the table, affecting "
              f"{len(unconverted)} names:")
        for ch, n in missing.most_common():
            print(f"       {ch}  (U+{ord(ch):04X})  x{n}")
        for code, name, kr, miss in unconverted[:20]:
            print(f"       {code} {name} -> {kr}   missing={miss}")
        print("     add these to hanja_kr._TABLE and rerun.")
    else:
        print("  every hanja in every name is mapped")

    body = [
        '"""names_auto.py -- GENERATED by gen_names_auto.py. Do not hand-edit.',
        "",
        "한자 종목명의 기계적 음독. 실제로 쓰는 이름은 names.py의 NAME_KR에서",
        "덮어쓴다 (그쪽이 우선). 이 파일은 재생성하면 통째로 덮어써진다.",
        "",
        f"reference month: {ref}    companies: {len(rows)}",
        f"unmapped hanja : {len(missing)}",
        '"""',
        "",
        "NAME_AUTO = {",
    ]
    for r in rows:
        code = r["code"]
        en = (r["name_en"] or "").replace('"', "'")
        body.append(f'    "{code}": "{out[code]}",'.ljust(34)
                    + f'# {r["name"]}  {en}')
    body.append("}")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(body) + "\n")

    size = os.path.getsize(OUT)
    print(f"\nwrote {OUT}  {len(out)} entries, {size:,} bytes")
    print("  samples:")
    for r in rows[:8]:
        print(f"    {r['code']} {r['name']:<12} -> {out[r['code']]}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
